# Generated by Django 3.2.3 on 2021-06-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=6, max_digits=7)),
                ('cg_url', models.URLField()),
                ('tg_url', models.URLField()),
                ('text', models.TextField()),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
    ]
