# Generated by Django 3.2.3 on 2021-06-03 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210603_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_added',
        ),
    ]
