# Generated by Django 3.2.3 on 2021-06-03 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_post_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='coin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='news.coin'),
        ),
    ]
