# Generated by Django 3.2.3 on 2021-06-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_pricedynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedynamic',
            name='cg_id',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
