# Generated by Django 3.2.3 on 2021-06-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_pricedynamic_coin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinSubmit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=90)),
                ('cg_link', models.URLField()),
            ],
        ),
    ]
