# Generated by Django 3.2.3 on 2021-07-18 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_alter_post_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
